name: Retrieve DB Ticket
description: |
  Based on PR information check for existing DB ticket and return url

inputs:
  github-repository:
    required: true
    type: string
  JIRA_TOKEN_DB:
    description: Jira token for authentication
    required: true
    type: string
  pr-url:
    required: true
    type: string

outputs:
  jira_ticket_link:
    description: Link to the created Jira ticket
    value: ${{ steps.get_ticket_url.outputs.jira_ticket_link}}

runs:
  using: "composite"
  steps:
    - id: get_ticket_url
      env:
        JIRA_TOKEN_DB: ${{ inputs.JIRA_TOKEN_DB }}
        REPO_NAME: ${{ inputs.github-repository}}
        PR_URL: ${{ toJson(inputs.pr-url) }}
      run: |
        python -m pip install requests   #Install necessary packages
        python ${{ github.action_path }}/get_ticket_url.py

      shell: bash
