GRANT USAGE ON SCHEMA dal_us TO group dal_read;
GRANT USAGE ON SCHEMA dal_us TO group dal_write;
GRANT USAGE ON SCHEMA dal_us TO group dal_write;
GRANT ALL ON SCHEMA dal_us TO group dal_modify;
GRANT USAGE ON SCHEMA dal_eu TO group dal_read;
GRANT USAGE ON SCHEMA dal_eu TO group dal_write;
GRANT USAGE ON SCHEMA dal_eu TO group dal_write;
GRANT ALL ON SCHEMA dal_eu TO group dal_modify;
GRANT USAGE ON SCHEMA stg_dal_us TO group dal_read;
GRANT USAGE ON SCHEMA stg_dal_us TO group dal_write;
GRANT USAGE ON SCHEMA stg_dal_us TO group dal_write;
GRANT ALL ON SCHEMA stg_dal_us TO group dal_modify;
GRANT USAGE ON SCHEMA stg_dal_eu TO group dal_read;
GRANT USAGE ON SCHEMA stg_dal_eu TO group dal_write;
GRANT USAGE ON SCHEMA stg_dal_eu TO group dal_write;
GRANT ALL ON SCHEMA stg_dal_eu TO group dal_modify;
GRANT SELECT ON ALL tables IN SCHEMA dal_us TO group dal_read;
GRANT SELECT ON ALL tables IN SCHEMA dal_eu TO group dal_read;
GRANT SELECT ON ALL tables IN SCHEMA stg_dal_us TO group dal_read;
GRANT SELECT ON ALL tables IN SCHEMA stg_dal_eu TO group dal_read;
GRANT INSERT ON ALL tables IN SCHEMA dal_us TO group dal_write;
GRANT UPDATE ON ALL tables IN SCHEMA dal_us TO group dal_write;
GRANT DELETE ON ALL tables IN SCHEMA dal_us TO group dal_write;
GRANT INSERT ON ALL tables IN SCHEMA dal_eu TO group dal_write;
GRANT UPDATE ON ALL tables IN SCHEMA dal_eu TO group dal_write;
GRANT DELETE ON ALL tables IN SCHEMA dal_eu TO group dal_write;
GRANT INSERT ON ALL tables IN SCHEMA stg_dal_us TO group dal_write;
GRANT UPDATE ON ALL tables IN SCHEMA stg_dal_us TO group dal_write;
GRANT DELETE ON ALL tables IN SCHEMA stg_dal_us TO group dal_write;
GRANT INSERT ON ALL tables IN SCHEMA stg_dal_eu TO group dal_write;
GRANT UPDATE ON ALL tables IN SCHEMA stg_dal_eu TO group dal_write;
GRANT DELETE ON ALL tables IN SCHEMA stg_dal_eu TO group dal_write;
GRANT EXECUTE ON ALL functions IN SCHEMA dal_us TO group dal_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA dal_us TO group dal_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA dal_eu TO group dal_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA dal_eu TO group dal_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA stg_dal_us TO group dal_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA stg_dal_us TO group dal_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA stg_dal_eu TO group dal_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA stg_dal_eu TO group dal_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA dal_us TO group dal_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA dal_eu TO group dal_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA stg_dal_us TO group dal_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA stg_dal_eu TO group dal_modify;
GRANT USAGE ON SCHEMA dal_ctrl TO group dal_read;
GRANT USAGE ON SCHEMA dal_ctrl TO group dal_write;
GRANT USAGE ON SCHEMA dal_ctrl TO group dal_execute;
GRANT ALL ON SCHEMA dal_ctrl TO group dal_modify;
GRANT SELECT ON ALL tables IN SCHEMA dal_ctrl TO group dal_read;
GRANT INSERT ON ALL tables IN SCHEMA dal_ctrl TO group dal_write;
GRANT UPDATE ON ALL tables IN SCHEMA dal_ctrl TO group dal_write;
GRANT DELETE ON ALL tables IN SCHEMA dal_ctrl TO group dal_write;
GRANT EXECUTE ON ALL functions IN SCHEMA dal_ctrl TO group dal_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA dal_ctrl TO group dal_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA dal_ctrl TO group dal_modify;
GRANT USAGE ON SCHEMA sqlrds_us TO group db_read;
GRANT USAGE ON SCHEMA sqlrds_eu TO group db_read;
GRANT USAGE ON SCHEMA sqlrds_us TO group db_write;
GRANT USAGE ON SCHEMA sqlrds_eu TO group db_write;
GRANT USAGE ON SCHEMA sqlrds_us TO group db_execute;
GRANT USAGE ON SCHEMA sqlrds_eu TO group db_execute;
GRANT ALL ON SCHEMA sqlrds_us TO group db_modify;
GRANT ALL ON SCHEMA sqlrds_eu TO group db_modify;
GRANT SELECT ON ALL tables IN SCHEMA sqlrds_us TO group db_read;
GRANT SELECT ON ALL tables IN SCHEMA sqlrds_eu TO group db_read;
GRANT INSERT ON ALL tables IN SCHEMA sqlrds_us TO group db_write;
GRANT INSERT ON ALL tables IN SCHEMA sqlrds_eu TO group db_write;
GRANT UPDATE ON ALL tables IN SCHEMA sqlrds_us TO group db_write;
GRANT UPDATE ON ALL tables IN SCHEMA sqlrds_eu TO group db_write;
GRANT DELETE ON ALL tables IN SCHEMA sqlrds_us TO group db_write;
GRANT DELETE ON ALL tables IN SCHEMA sqlrds_eu TO group db_write;
GRANT EXECUTE ON ALL functions IN SCHEMA sqlrds_eu TO group db_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA sqlrds_us TO group db_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA sqlrds_eu TO group db_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA sqlrds_us TO group db_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA sqlrds_us TO group db_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA sqlrds_eu TO group db_modify;
GRANT USAGE ON SCHEMA use_lake TO group lake_read;
GRANT USAGE ON SCHEMA use_lake TO group lake_write;
GRANT USAGE ON SCHEMA use_lake TO group lake_write;
GRANT ALL ON SCHEMA use_lake TO group lake_modify;
GRANT USAGE ON SCHEMA euw_lake TO group lake_read;
GRANT USAGE ON SCHEMA euw_lake TO group lake_write;
GRANT USAGE ON SCHEMA euw_lake TO group lake_write;
GRANT ALL ON SCHEMA euw_lake TO group lake_modify;
GRANT SELECT ON ALL tables IN SCHEMA use_lake TO group lake_read;
GRANT INSERT ON ALL tables IN SCHEMA use_lake TO group lake_write;
GRANT UPDATE ON ALL tables IN SCHEMA use_lake TO group lake_write;
GRANT DELETE ON ALL tables IN SCHEMA use_lake TO group lake_write;
GRANT SELECT ON ALL tables IN SCHEMA euw_lake TO group lake_read;
GRANT INSERT ON ALL tables IN SCHEMA euw_lake TO group lake_write;
GRANT UPDATE ON ALL tables IN SCHEMA euw_lake TO group lake_write;
GRANT DELETE ON ALL tables IN SCHEMA euw_lake TO group lake_write;
GRANT EXECUTE ON ALL functions IN SCHEMA use_lake TO group lake_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA use_lake TO group lake_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA euw_lake TO group lake_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA euw_lake TO group lake_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA use_lake TO group lake_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA euw_lake TO group lake_modify;
GRANT USAGE ON SCHEMA payers1_lake TO group payers1_lake_read;
GRANT USAGE ON SCHEMA payers1_lake TO group payers1_lake_write;
GRANT USAGE ON SCHEMA payers1_lake TO group payers1_lake_write;
GRANT ALL ON SCHEMA payers1_lake TO group payers1_lake_modify;
GRANT SELECT ON ALL tables IN SCHEMA payers1_lake TO group payers1_lake_read;
GRANT INSERT ON ALL tables IN SCHEMA payers1_lake TO group payers1_lake_write;
GRANT UPDATE ON ALL tables IN SCHEMA payers1_lake TO group payers1_lake_write;
GRANT DELETE ON ALL tables IN SCHEMA payers1_lake TO group payers1_lake_write;
GRANT EXECUTE ON ALL functions IN SCHEMA payers1_lake TO group payers1_lake_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA payers1_lake TO group payers1_lake_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA payers1_lake TO group payers1_lake_modify;
GRANT USAGE ON SCHEMA salesforce_us TO group salesforce_read;
GRANT USAGE ON SCHEMA salesforce_us TO group salesforce_write;
GRANT USAGE ON SCHEMA salesforce_us TO group salesforce_write;
GRANT ALL ON SCHEMA salesforce_us TO group salesforce_modify;
GRANT USAGE ON SCHEMA salesforce_eu TO group salesforce_read;
GRANT USAGE ON SCHEMA salesforce_eu TO group salesforce_write;
GRANT USAGE ON SCHEMA salesforce_eu TO group salesforce_write;
GRANT ALL ON SCHEMA salesforce_eu TO group salesforce_modify;
GRANT SELECT ON ALL tables IN SCHEMA salesforce_us TO group salesforce_read;
GRANT SELECT ON ALL tables IN SCHEMA salesforce_eu TO group salesforce_read;
GRANT INSERT ON ALL tables IN SCHEMA salesforce_us TO group salesforce_write;
GRANT UPDATE ON ALL tables IN SCHEMA salesforce_us TO group salesforce_write;
GRANT DELETE ON ALL tables IN SCHEMA salesforce_us TO group salesforce_write;
GRANT INSERT ON ALL tables IN SCHEMA salesforce_eu TO group salesforce_write;
GRANT UPDATE ON ALL tables IN SCHEMA salesforce_eu TO group salesforce_write;
GRANT DELETE ON ALL tables IN SCHEMA salesforce_eu TO group salesforce_write;
GRANT EXECUTE ON ALL functions IN SCHEMA salesforce_us TO group salesforce_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA salesforce_us TO group salesforce_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA salesforce_eu TO group salesforce_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA salesforce_eu TO group salesforce_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA salesforce_us TO group salesforce_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA salesforce_eu TO group salesforce_modify;
GRANT USAGE ON SCHEMA util TO group db_read;
GRANT USAGE ON SCHEMA util TO group db_write;
GRANT USAGE ON SCHEMA util TO group db_execute;
GRANT ALL ON SCHEMA util TO group db_modify;
GRANT SELECT ON ALL tables IN SCHEMA util TO group db_read;
GRANT INSERT ON ALL tables IN SCHEMA util TO group db_write;
GRANT UPDATE ON ALL tables IN SCHEMA util TO group db_write;
GRANT DELETE ON ALL tables IN SCHEMA util TO group db_write;
GRANT EXECUTE ON ALL functions IN SCHEMA util TO group db_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA util TO group db_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA util TO group db_modify;
GRANT USAGE ON SCHEMA dynamodb_us TO group dynamodb_read;
GRANT USAGE ON SCHEMA dynamodb_us TO group dynamodb_write;
GRANT USAGE ON SCHEMA dynamodb_us TO group dynamodb_write;
GRANT ALL ON SCHEMA dynamodb_us TO group dynamodb_modify;
GRANT USAGE ON SCHEMA dynamodb_eu TO group dynamodb_read;
GRANT USAGE ON SCHEMA dynamodb_eu TO group dynamodb_write;
GRANT USAGE ON SCHEMA dynamodb_eu TO group dynamodb_write;
GRANT ALL ON SCHEMA dynamodb_eu TO group dynamodb_modify;
GRANT USAGE ON SCHEMA dynamodb_ca TO group dynamodb_read;
GRANT USAGE ON SCHEMA dynamodb_ca TO group dynamodb_write;
GRANT USAGE ON SCHEMA dynamodb_ca TO group dynamodb_write;
GRANT ALL ON SCHEMA dynamodb_ca TO group dynamodb_modify;
GRANT SELECT ON ALL tables IN SCHEMA dynamodb_us TO group dynamodb_read;
GRANT SELECT ON ALL tables IN SCHEMA dynamodb_eu TO group dynamodb_read;
GRANT SELECT ON ALL tables IN SCHEMA dynamodb_ca TO group dynamodb_read;
GRANT INSERT ON ALL tables IN SCHEMA dynamodb_us TO group dynamodb_write;
GRANT UPDATE ON ALL tables IN SCHEMA dynamodb_us TO group dynamodb_write;
GRANT DELETE ON ALL tables IN SCHEMA dynamodb_us TO group dynamodb_write;
GRANT INSERT ON ALL tables IN SCHEMA dynamodb_eu TO group dynamodb_write;
GRANT UPDATE ON ALL tables IN SCHEMA dynamodb_eu TO group dynamodb_write;
GRANT DELETE ON ALL tables IN SCHEMA dynamodb_eu TO group dynamodb_write;
GRANT INSERT ON ALL tables IN SCHEMA dynamodb_ca TO group dynamodb_write;
GRANT UPDATE ON ALL tables IN SCHEMA dynamodb_ca TO group dynamodb_write;
GRANT DELETE ON ALL tables IN SCHEMA dynamodb_ca TO group dynamodb_write;
GRANT EXECUTE ON ALL functions IN SCHEMA dynamodb_us TO group dynamodb_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA dynamodb_us TO group dynamodb_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA dynamodb_eu TO group dynamodb_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA dynamodb_eu TO group dynamodb_execute;
GRANT EXECUTE ON ALL functions IN SCHEMA dynamodb_ca TO group dynamodb_execute;
GRANT EXECUTE ON ALL procedures IN SCHEMA dynamodb_ca TO group dynamodb_execute;
GRANT REFERENCES ON ALL tables IN SCHEMA dynamodb_us TO group dynamodb_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA dynamodb_eu TO group dynamodb_modify;
GRANT REFERENCES ON ALL tables IN SCHEMA dynamodb_ca TO group dynamodb_modify;