USE [master]
GO

CREATE SERVER AUDIT SPECIFICATION [SrvAudit_Spec_Server_Security]
FOR SERVER AUDIT [SQLAudit]
	ADD (AUDIT_CHANGE_GROUP),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
	ADD (SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP)
GO

ALTER SERVER AUDIT SPECIFICATION [SrvAudit_Spec_Server_Security]
WITH (STATE = ON)
GO

CREATE SERVER AUDIT SPECIFICATION [SrvAudit_Spec_logins]
FOR SERVER AUDIT [LoginAudit]
	ADD (SUCCESSFUL_LOGIN_GROUP),
	ADD (FAILED_LOGIN_GROUP)
GO

ALTER SERVER AUDIT SPECIFICATION [SrvAudit_Spec_logins]
WITH (STATE = ON)
GO
