def get_cortex_tag(i):
    switcher = {
        'dev-2019-std-eu': 'rds-sql-dev-eu',
        'dev-nicelabel': 'nicelabel-dev-eu',
        'elsadb-dev-euw': 'elsadb-dev-eu',
        'dev-2019-std-us': 'rds-sql-dev-us',
        'elsadb-dev-use': 'elsadb-dev-us',
        'firelydb-use': 'firelydb-dev-us',
        'elsadb-stg-euw': 'elsadb-stg-eu',
        'staging': 'rds-sql-stg-eu',
        'datahubdb-stg': 'datahub-stg-us',
        'elsadb-stg-use': 'elsadb-stg-us',
        'firelydb-use': 'firelydb-stg-us',
        'staging': 'rds-sql-stg-us',
        'pro-main3-db': 'rds-sql-prod-eu',
        'pro-firelydb2-use': 'firelydb-prod-us',
        'pro-main2-db': 'rds-sql-prod-us',
        'database-laurora-v2-cluster': 'laurora-stg-us',
        'ds-stg-biotail-rds-aurora-cluster': 'biotail-stg-us',
        'database-laurora-instance-1': 'laurora-prod-us',
        'ds-prd-biotail-rds-aurora-instance-1': 'biotail-prod-us',
        'datascprod-us-db-st1': 'ds-sql-prod-us-1',
        'datascprod-us-db-st2': 'ds-sql-prod-us-2',
        'prod-nicelabel': 'nicelabel-prod-us',
        'produps-db': 'ups-prod-EU',
        'prod-octopus': 'octopus-prod-eu',
        'vg-qa': 'company-vg-stg-us',
        'vi-qa': 'company-vi-stg-eu',
        'companygeointernal': 'company-vi-prod-us',
        'companygeopublic': 'company-vg-prod-us',
        'staging-idp': 'idp-stg-us',
        'prod-idp': 'idp-prod-us'
    }
    return switcher.get(i, 'No Cortex Tag Found')
