name: Create DB Project Ticket

# Allows the workflow to be triggered manually from the Actions tab in GitHub.
on:
  workflow_dispatch
  # The 'pull_request' trigger is currently commented out.
  # If enabled, it would run the workflow automatically when a pull request is
  # opened, edited, reopened, or has new commits pushed.
  ##pull_request:
  ##types: [opened, synchronize]
jobs:
  sql-file-check:
    runs-on: ubuntu-latest
    outputs:
      github-repository: ${{ steps.variable-set.outputs.github-repository }}
      head-ref: ${{ steps.variable-set.outputs.head-ref }}
      pr-url: ${{ steps.variable-set.outputs.pr-url }}
      repo-name: ${{ steps.variable-set.outputs.repo-name }}
      sql-files-altered: ${{steps.fileID.outputs.DIFFS}}
      sql-files-list: ${{steps.fileID.outputs.SQL_FILES}}
    steps:
      - id: repoCheckout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}

      - id: fileID
        shell: bash
        run: |
          current_commit=$(git rev-parse HEAD)
          previous_commit=$(git rev-parse HEAD^1)
          SQL_FILES=$(git diff --name-only -r $previous_commit $current_commit *.sql)  
          if [ -z "$SQL_FILES" ]; then
          echo "No SQL files changed."
          echo "DIFFS=0" >> $GITHUB_OUTPUT
          else
          echo "SQL files changed: $SQL_FILES"
          FILE_LIST=''
          for i in $SQL_FILES
          do
              FILE_LIST+="$i "
          done
          echo "SQL_FILES=$FILE_LIST" >> $GITHUB_OUTPUT
          echo "DIFFS=1" >> $GITHUB_OUTPUT
          fi

      - id: variable-set
        run: |
          echo "github-repository=${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "head-ref=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          echo "pr-url=${{ toJson(github.event.pull_request._links.html.href) }}" >> $GITHUB_OUTPUT
          echo "repo-name=${{ toJson(github.repository) }}" >> $GITHUB_OUTPUT

  create-db-ticket:
    needs: sql-file-check
    uses: ./.github/workflows/create_db_ticket_general.yml
    with:
      github-repository: ${{ needs.sql-file-check.outputs.github-repository }}
      head-ref: ${{ needs.sql-file-check.outputs.head-ref }}
      pr-url: ${{ needs.sql-file-check.outputs.pr-url }}
      repo-name: ${{ needs.sql-file-check.outputs.repo-name }}
      sql-files-altered: ${{ needs.sql-file-check.outputs.sql-files-altered }}
      sql-files-list: ${{ needs.sql-file-check.outputs.sql-files-list }}
    secrets: inherit
