name: Send DBA Review Request

# Allows the workflow to be triggered manually from the Actions tab in GitHub.
on:
  workflow_dispatch
  # The 'issue_comment' trigger is currently commented out.
  # If enabled, it would run the workflow automatically when a comment is pushed.
  ##issue_comment

jobs:
  variable-set:
    if: ${{ github.event.issue.pull_request != null && contains(github.event.comment.body,'@Company/dba review requested') }}
    runs-on: ubuntu-latest
    outputs:
      github-repository: ${{ steps.set-vars.outputs.github-repository }}
      pr-url: ${{ steps.set-vars.outputs.pr-url }}
      user: ${{ steps.set-vars.outputs.user }}
    steps:
      - id: set-vars
        run: |
          echo "github-repository=${{ github.event.repository.full_name }}" >> $GITHUB_OUTPUT
          echo "pr-url=${{ toJson(github.event.issue.html_url) }}" >> $GITHUB_OUTPUT
          echo "user=${{ github.event.comment.user.login }}" >> $GITHUB_OUTPUT

  dba_review_request:
    needs: variable-set
    uses: ./.github/workflows/dba_review_request_general.yml@main
    with:
      github-repository: ${{ needs.variable-set.outputs.github-repository }}
      pr-url: ${{ needs.variable-set.outputs.pr-url }}
      user: ${{ needs.variable-set.outputs.user }}
    secrets: inherit
