name: Send DBA Review Request

on:
    workflow_call:
        inputs:
            github-repository:
                required: true
                type: string
            pr-url:
                required: true
                type: string
            user:
                required: true
                type: string

jobs:
    identify-existing-ticket:
        runs-on: ubuntu-latest
        outputs:
            jira_ticket_link: ${{ steps.get_ticket_url.outputs.jira_ticket_link }}
        steps:
            - id: repoCheckout
              uses: actions/checkout@v4

            - name: Retrieve DB Ticket URL
              id: get_ticket_url
              uses: ./.github/actions/Jira/retrieve-db-ticket@main
              with:
                  JIRA_TOKEN_DB: ${{ secrets.JIRA_TOKEN_DB }}
                  github-repository: ${{ inputs.github-repository}}
                  pr-url: ${{ toJson(inputs.pr-url) }}

            - name: Send Slack Notification to DBA Channel
              id: slack_notification_send
              if: ${{ steps.get_ticket_url.outputs.jira_ticket_link != '' }}
              uses: ./.github/actions/Slack/dba-slack-notification@main
              with:
                  message_form: "review_requested"
                  pr-number: ${{ github.event.pull_request.number }}
                  repo-name: ${{ inputs.repo-name }}
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
                  ticket_url: ${{ steps.get_ticket_url.outputs.jira_ticket_link }}
                  user: ${{ inputs.user }}
